sudo: false
language: ruby

rvm:
- ruby-head
- 2.3.0
- 2.2
- 2.1
- 2.0
#- jruby-9000
- jruby-9.0.4.0
- rbx-2

cache:
- bundler

matrix:
  allow_failures:
#    - rvm: jruby-9000
    - rvm: jruby-9.0.4.0
    - rvm: rbx-2
