name: Test

on: [push, pull_request]

jobs:
  test:
    name: Ruby ${{ matrix.ruby }} (${{ matrix.os }})
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        ruby:
        - 3.0
        - 2.7
        - 2.6
        - 2.5
        os:
        - ubuntu-latest
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake
